---
# tasks file for unattended_upgrades (Ubuntu specific)

- name: Install unattended upgrades packages
  apt: name={{ item }} state=present update_cache=yes
  with_items: unattended_upgrades_packages
  tags: unattended_upgrades

- name: Create unattended upgrades APT configuration file
  template: >
    src=unattended_upgrades.conf.j2
    dest=/etc/apt/apt.conf.d/50unattended-upgrades
    owner=root
    group=root
    mode=0644
  tags: unattended_upgrades
